version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: wellnesshubDB
      POSTGRES_USER:  postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data: