version: '3.8'

services:
  db:
    image: postgres:17-alpine
    container_name: my-postgres-db
    environment:
      POSTGRES_DB: wellnesshubDB
      POSTGRES_USER: wellnesshub
      POSTGRES_PASSWORD: wellnesshub
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always

volumes:
  db_data: